### ISSUE TITLE
Null safety

### ISSUE THREAD

**Issue by DanieLeeuwner** [NaveenGurram/random-date#1]
Are you planning to migrate this package to null safety?

**Comment by NaveenGurram** [comment]
@DanieLeeuwner  can you provide a example that is giving out  a Null Pointer exception?

**Comment by timonschapeler** [comment]
I have the same problem just by importing:
"import 'package:random_date/random_date.dart';"

This will result in:
"Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

 - package:random_date"

**Comment by NaveenGurram** [comment]
fixed, please get the latest version 0.0.6 https://pub.dev/packages/random_date
